name: cupertino_modal_sheet
description: Shows a modal iOS-style sheet that slides up from the bottom of the screen.
version: 1.0.0
homepage: https://github.com/zuvola/cupertino_modal_sheet

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
